name: Draw ZMK keymaps
on:
  workflow_dispatch:
  push:
    paths:
      - "config/**"
      - ".github/workflows/draw-keymaps.yml"

permissions:
  contents: write

jobs:
  draw:
    uses: caksoylar/keymap-drawer/.github/workflows/draw-zmk.yml@main
    permissions:
      contents: write
    with:
      keymap_patterns: "config/corne.keymap"
      output_folder: "keymap-drawer"
      west_config_path: "config"
      config_path: "keymap_drawer.config.yaml"
      amend_commit: false
      install_branch: "main"
